ALTER TABLE public.racuni
ADD COLUMN IF NOT EXISTS zki VARCHAR(32),
ADD COLUMN IF NOT EXISTS jir VARCHAR(36),
ADD COLUMN IF NOT EXISTS fiskalizirano_at TIMESTAMPTZ,
ADD COLUMN IF NOT EXISTS fiskalizacija_error TEXT;
